---
language: node_js
node_js:
  - "6"

dist: trusty
sudo: required

addons:
  apt:
    sources:
    - google-chrome
    packages:
    - google-chrome-stable
  hosts:
    - localhost.firebaseio.test

cache:
  directories:
    - node_modules
    - bower_components

before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "npm config set spin false"
  - "npm install -g npm@^3"

install:
  - npm install

script:
  - npm run lint:js
  - npm test
